<?php
require __DIR__.'/inc/bootstrap.php';
require_auth();
require_once __DIR__.'/inc/cash_flow.php';
require __DIR__.'/inc/layout.php';
try{cashflow_sync_evotor_payments();}catch(Throwable $e){}
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$a=(string)($_POST['action']??'');
 try{
  if($a==='manual'){$id=cashflow_manual_entry((int)$_POST['account_id'],(string)$_POST['direction'],(string)$_POST['entry_type'],(float)$_POST['amount'],(string)($_POST['occurred_at']??date('Y-m-d H:i:s')),trim((string)($_POST['category']??'')),trim((string)($_POST['description']??'')));audit_write('cashflow_entry_created','Добавлена денежная операция','cash_flow_entry',(string)$id);flash('success','Операция добавлена.');}
  elseif($a==='transfer'){cashflow_transfer((int)$_POST['from_id'],(int)$_POST['to_id'],(float)$_POST['amount'],(string)($_POST['occurred_at']??date('Y-m-d H:i:s')),'transfer',trim((string)($_POST['description']??'')));audit_write('cashflow_transfer','Перевод между денежными счетами');flash('success','Перевод сохранён.');}
  elseif($a==='electron_settlement'){cashflow_settle_electronic((float)$_POST['gross_amount'],(float)$_POST['fee_amount'],(int)$_POST['bank_account_id'],(string)($_POST['occurred_at']??date('Y-m-d H:i:s')),trim((string)($_POST['description']??'Зачисление безналичных продаж')));audit_write('electron_settlement','Зачисление безналичных продаж');flash('success','Безналичное зачисление учтено.');}
  elseif($a==='opening'){cashflow_set_opening_balance((int)$_POST['account_id'],(float)$_POST['opening_balance']);flash('success','Начальный остаток обновлён.');}
  elseif($a==='account'){cashflow_update_account((int)$_POST['account_id'],(string)$_POST['name'],(string)($_POST['provider']??''),isset($_POST['active']));flash('success','Денежный счёт обновлён.');}
 }catch(Throwable $e){flash('danger',$e->getMessage());}
 redirect('cash_flow.php');
}
$to=$_GET['to']??date('Y-m-d');$from=$_GET['from']??date('Y-m-d',strtotime('-29 days'));
$accounts=cashflow_balances();$summary=cashflow_summary($from,$to);$runway=cashflow_runway_days(30);$pending=cashflow_electronic_pending();$pvsm=cashflow_profit_vs_money($from,$to);
$liquid=0.0;foreach($accounts as $a){if(in_array($a['account_type'],['cash','bank'],true))$liquid+=(float)$a['balance'];}
$banks=array_values(array_filter($accounts,fn($a)=>$a['account_type']==='bank'&&(int)$a['active']===1));
page_header('Денежный поток');
?>
<div class="card filter-card"><form method="get" style="display:contents"><label>С<input type="date" name="from" value="<?=e($from)?>"></label><label>По<input type="date" name="to" value="<?=e($to)?>"></label><button class="btn primary">Показать</button></form></div>
<div class="grid section">
 <div class="card metric"><div class="label">Ликвидные деньги</div><div class="value"><?=money($liquid)?></div><div class="meta">Касса + банковские счета в Kapouch</div></div>
 <div class="card metric"><div class="label">Безнал / ожидаемые поступления</div><div class="value"><?=money($pending)?></div><div class="meta">Электронные оплаты из Эвотор до фактического зачисления</div></div>
 <div class="card metric"><div class="label">Операционный Cash Flow</div><div class="value"><?=money($summary['operating_net'])?></div><div class="meta">За выбранный период</div></div>
 <div class="card metric"><div class="label">Cash runway</div><div class="value"><?=$runway===null?'—':number_format($runway,1,',',' ')?></div><div class="meta">дней при текущем темпе расходов</div></div>
</div>
<div class="two-col section">
 <div class="card"><div class="chart-head"><div><h2>Прибыль vs деньги</h2><p>Управленческая прибыль и фактический денежный поток.</p></div></div><table><tbody><tr><td>Операционная прибыль</td><td><strong><?=money($pvsm['operating_profit'])?></strong></td></tr><tr><td>Операционный Cash Flow</td><td><strong><?=money($pvsm['cashflow_operating_net'])?></strong></td></tr><tr><td>Разница</td><td><strong><?=($pvsm['difference']>=0?'+':'').money($pvsm['difference'])?></strong></td></tr></tbody></table></div>
 <div class="card"><div class="chart-head"><div><h2>Зачисление безналичных продаж</h2><p>Эвотор сообщает тип `ELECTRON`, но не подтверждает конкретный банк.</p></div></div><?php if($banks):?><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="electron_settlement"><label>Банковский счёт<select name="bank_account_id"><?php foreach($banks as $a):?><option value="<?=$a['id']?>"><?=e($a['name'])?></option><?php endforeach;?></select></label><label>Дата и время<input type="datetime-local" name="occurred_at" value="<?=date('Y-m-d\TH:i')?>"></label><label>Сумма до комиссии<input type="number" min="0.01" step="0.01" name="gross_amount" required></label><label>Комиссия<input type="number" min="0" step="0.01" name="fee_amount" value="0"></label><label>Комментарий<input name="description" value="Зачисление безналичных продаж"></label><button class="btn primary">Учесть зачисление</button></form><?php else:?><div class="alert warning">Нет активного банковского счёта.</div><?php endif;?></div>
</div>
<div class="card table-card section"><div class="chart-head"><div><h2>Денежные счета</h2><p>Банковский счёт можно переименовать под фактический банк. Остатки пока ведутся вручную.</p></div></div><table><thead><tr><th>Счёт</th><th>Тип</th><th>Источник</th><th>Начальный остаток</th><th>Расчётный остаток</th><th>Настройка</th></tr></thead><tbody><?php foreach($accounts as $a):?><tr><td><strong><?=e($a['name'])?></strong></td><td><?=e($a['account_type'])?></td><td><?=e((string)($a['provider']??'—'))?></td><td><?=money((float)$a['opening_balance'])?></td><td><strong><?=money((float)$a['balance'])?></strong></td><td><details><summary class="btn ghost">Настроить</summary><form method="post" class="stack" style="margin-top:10px;min-width:250px"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="account"><input type="hidden" name="account_id" value="<?=$a['id']?>"><label>Название<input name="name" value="<?=e($a['name'])?>" required></label><label>Банк / источник<input name="provider" value="<?=e((string)$a['provider'])?>"></label><label><input type="checkbox" name="active" value="1" <?=(int)$a['active']?'checked':''?>> Активен</label><button class="btn">Сохранить</button></form><form method="post" class="stack" style="margin-top:10px"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="opening"><input type="hidden" name="account_id" value="<?=$a['id']?>"><label>Начальный остаток<input type="number" step="0.01" name="opening_balance" value="<?=e((string)$a['opening_balance'])?>"></label><button class="btn ghost">Изменить остаток</button></form></details></td></tr><?php endforeach;?></tbody></table></div>
<div class="two-col section">
 <div class="card"><div class="chart-head"><div><h2>Ручная операция</h2><p>Банковские расходы, поступления, вложения и выводы владельца.</p></div></div><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="manual"><label>Счёт<select name="account_id"><?php foreach($accounts as $a):if(!(int)$a['active'])continue;?><option value="<?=$a['id']?>"><?=e($a['name'])?></option><?php endforeach;?></select></label><div class="form-grid"><label>Направление<select name="direction"><option value="out">Расход</option><option value="in">Поступление</option></select></label><label>Тип<select name="entry_type"><option value="expense">Расход</option><option value="purchase">Закупка</option><option value="owner_in">Вложение владельца</option><option value="owner_out">Вывод владельца</option><option value="fee">Комиссия</option><option value="other">Другое</option></select></label><label>Сумма<input type="number" min="0.01" step="0.01" name="amount" required></label></div><label>Дата и время<input type="datetime-local" name="occurred_at" value="<?=date('Y-m-d\TH:i')?>"></label><label>Категория<input name="category"></label><label>Комментарий<input name="description"></label><button class="btn primary">Добавить</button></form></div>
 <div class="card"><div class="chart-head"><div><h2>Перевод между счетами</h2><p>Перевод не считается доходом или расходом.</p></div></div><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="transfer"><label>Со счёта<select name="from_id"><?php foreach($accounts as $a):if(!(int)$a['active'])continue;?><option value="<?=$a['id']?>"><?=e($a['name'])?></option><?php endforeach;?></select></label><label>На счёт<select name="to_id"><?php foreach($accounts as $a):if(!(int)$a['active'])continue;?><option value="<?=$a['id']?>"><?=e($a['name'])?></option><?php endforeach;?></select></label><label>Сумма<input type="number" min="0.01" step="0.01" name="amount" required></label><label>Дата и время<input type="datetime-local" name="occurred_at" value="<?=date('Y-m-d\TH:i')?>"></label><label>Комментарий<input name="description"></label><button class="btn">Сохранить перевод</button></form></div>
</div>
<div class="card table-card section"><div class="chart-head"><div><h2>Движение денег</h2><p>CASH и ELECTRON из Эвотор синхронизируются автоматически.</p></div></div><table><thead><tr><th>Дата</th><th>Счёт</th><th>Операция</th><th>Сумма</th><th>Описание</th></tr></thead><tbody><?php foreach(array_slice($summary['rows'],0,300) as $r):?><tr><td><?=e(date('d.m.Y H:i',strtotime($r['occurred_at'])))?></td><td><?=e($r['account_name'])?></td><td><?=e($r['entry_type'])?></td><td><strong><?=$r['direction']==='in'?'+':'−'?><?=money((float)$r['amount'])?></strong></td><td><?=e((string)($r['description']??'—'))?></td></tr><?php endforeach;?></tbody></table></div>
<div class="alert warning section"><strong>Важно.</strong> `ELECTRON` означает электронную оплату, а не конкретно Сбербанк. Реальные банковские остатки сейчас задаются вручную; позже банковский API можно подключить к этой же модели.</div>
<?php page_footer(); ?>