<?php
require __DIR__.'/inc/bootstrap.php';
require __DIR__.'/inc/layout.php';
require_auth();
require_once __DIR__.'/inc/customer_modifiers.php';

if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$action=(string)($_POST['action']??'');
    try{
        if($action==='group_save'){
            $id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));if($name==='')throw new RuntimeException('Укажите название группы модификаторов.');
            $min=max(0,min(10,(int)($_POST['min_select']??0)));$max=max(1,min(10,(int)($_POST['max_select']??1)));if($min>$max)$min=$max;$sort=(int)($_POST['sort_order']??100);$active=isset($_POST['active'])?1:0;
            if($id){$stmt=db()->prepare('UPDATE customer_modifier_groups SET name=?,min_select=?,max_select=?,sort_order=?,active=? WHERE id=?');$stmt->execute([$name,$min,$max,$sort,$active,$id]);}
            else{$stmt=db()->prepare('INSERT INTO customer_modifier_groups(name,min_select,max_select,sort_order,active) VALUES(?,?,?,?,?)');$stmt->execute([$name,$min,$max,$sort,$active]);$id=(int)db()->lastInsertId();}
            audit_write('customer_modifier_group_saved','Группа модификаторов: '.$name,'customer_modifier_group',(string)$id);flash('success','Группа модификаторов сохранена.');
        }elseif($action==='option_save'){
            $groupId=(int)($_POST['modifier_group_id']??0);$productId=(int)($_POST['product_id']??0);if($groupId<=0||$productId<=0)throw new RuntimeException('Выберите группу и товар Evotor.');
            $label=mb_substr(trim((string)($_POST['label']??'')),0,120);$sort=(int)($_POST['sort_order']??100);$active=isset($_POST['active'])?1:0;
            $stmt=db()->prepare('INSERT INTO customer_modifier_options(modifier_group_id,product_id,label,sort_order,active) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE label=VALUES(label),sort_order=VALUES(sort_order),active=VALUES(active)');$stmt->execute([$groupId,$productId,$label?:null,$sort,$active]);flash('success','Модификатор связан с товаром Kapouch/Evotor.');
        }elseif($action==='option_delete'){
            db()->prepare('DELETE FROM customer_modifier_options WHERE id=?')->execute([(int)($_POST['id']??0)]);flash('success','Модификатор удалён из группы.');
        }elseif($action==='assign_group'){
            $displayGroupId=(int)($_POST['product_group_id']??0);$modifierGroupId=(int)($_POST['modifier_group_id']??0);if(!$displayGroupId||!$modifierGroupId)throw new RuntimeException('Выберите напиток и группу модификаторов.');db()->prepare('INSERT IGNORE INTO customer_display_group_modifier_groups(product_group_id,modifier_group_id) VALUES(?,?)')->execute([$displayGroupId,$modifierGroupId]);flash('success','Модификаторы подключены ко всей группе напитка.');
        }elseif($action==='assign_product'){
            $productId=(int)($_POST['product_id']??0);$modifierGroupId=(int)($_POST['modifier_group_id']??0);if(!$productId||!$modifierGroupId)throw new RuntimeException('Выберите товар и группу модификаторов.');db()->prepare('INSERT IGNORE INTO customer_product_modifier_groups(product_id,modifier_group_id) VALUES(?,?)')->execute([$productId,$modifierGroupId]);flash('success','Модификаторы подключены к товару.');
        }elseif($action==='assignment_delete'){
            $type=(string)($_POST['target_type']??'');$target=(int)($_POST['target_id']??0);$group=(int)($_POST['modifier_group_id']??0);if($type==='group')db()->prepare('DELETE FROM customer_display_group_modifier_groups WHERE product_group_id=? AND modifier_group_id=?')->execute([$target,$group]);elseif($type==='product')db()->prepare('DELETE FROM customer_product_modifier_groups WHERE product_id=? AND modifier_group_id=?')->execute([$target,$group]);flash('success','Привязка удалена.');
        }
    }catch(Throwable $e){flash('danger',$e->getMessage());}
    redirect('customer_modifiers.php');
}
$groups=customer_modifier_groups(false);$products=db()->query('SELECT id,name,sale_price,active FROM products ORDER BY active DESC,name')->fetchAll();$displayGroups=db()->query('SELECT id,name,visible FROM customer_product_groups ORDER BY sort_order,name')->fetchAll();
$options=[];foreach($groups as $g)$options[(int)$g['id']]=customer_modifier_options((int)$g['id'],false);
$assignGroups=db()->query('SELECT a.product_group_id,a.modifier_group_id,p.name product_group_name,m.name modifier_group_name FROM customer_display_group_modifier_groups a JOIN customer_product_groups p ON p.id=a.product_group_id JOIN customer_modifier_groups m ON m.id=a.modifier_group_id ORDER BY p.name,m.sort_order,m.name')->fetchAll();
$assignProducts=db()->query('SELECT a.product_id,a.modifier_group_id,p.name product_name,m.name modifier_group_name FROM customer_product_modifier_groups a JOIN products p ON p.id=a.product_id JOIN customer_modifier_groups m ON m.id=a.modifier_group_id ORDER BY p.name,m.sort_order,m.name')->fetchAll();
page_header('Модификаторы PWA');
?>
<div class="card"><div class="chart-head"><div><h2>Модификаторы, связанные с товарами Evotor</h2><p>Альтернативное молоко, сиропы, дополнительный шот и другие платные добавки используют существующие товарные карточки и их актуальную цену.</p></div><a class="btn ghost" href="customer_app.php">← Клиентское PWA</a></div></div>
<div class="alert info section"><strong>Как работает цена:</strong> Kapouch не хранит отдельную цену модификатора. При заказе берётся текущая <strong>цена привязанного товара</strong> из каталога Kapouch/Evotor. Поэтому изменение цены товара автоматически меняет цену добавки в PWA.</div>
<div class="card section"><div class="chart-head"><div><h2>Новая группа модификаторов</h2><p>Например «Молоко» (0–1), «Сиропы» (0–2), «Выберите молоко» (1–1).</p></div></div><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="group_save"><label>Название<input name="name" required placeholder="Альтернативное молоко"></label><label>Минимум выбора<input type="number" min="0" max="10" name="min_select" value="0"></label><label>Максимум выбора<input type="number" min="1" max="10" name="max_select" value="1"></label><label>Порядок<input type="number" name="sort_order" value="100"></label><label style="display:flex;align-items:center;gap:8px"><input style="width:auto" type="checkbox" name="active" checked> Активна</label><div><button class="btn primary">Создать группу</button></div></form></div>
<?php foreach($groups as $g):$gid=(int)$g['id'];?>
<div class="card section"><div class="chart-head"><div><h2><?=e($g['name'])?></h2><p>Выбор: <?=$g['min_select']?>–<?=$g['max_select']?> · вариантов <?=count($options[$gid]??[])?></p></div></div>
<form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="group_save"><input type="hidden" name="id" value="<?=$gid?>"><label>Название<input name="name" value="<?=e($g['name'])?>"></label><label>Минимум<input type="number" min="0" max="10" name="min_select" value="<?=$g['min_select']?>"></label><label>Максимум<input type="number" min="1" max="10" name="max_select" value="<?=$g['max_select']?>"></label><label>Порядок<input type="number" name="sort_order" value="<?=$g['sort_order']?>"></label><label style="display:flex;align-items:center;gap:8px"><input style="width:auto" type="checkbox" name="active" <?=$g['active']?'checked':''?>> Активна</label><div><button class="btn ghost">Сохранить</button></div></form>
<div style="overflow:auto;margin-top:14px"><table><thead><tr><th>Товар Kapouch / Evotor</th><th>Название в PWA</th><th>Цена</th><th>Статус</th><th></th></tr></thead><tbody><?php foreach($options[$gid]??[] as $o):?><tr><td><strong><?=e($o['product_name'])?></strong></td><td><?=e((string)($o['label']?:$o['product_name']))?></td><td><?=money((float)$o['sale_price'])?></td><td><?=($o['active']&&$o['product_active'])?'Активен':'Отключён'?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="option_delete"><input type="hidden" name="id" value="<?=$o['id']?>"><button class="btn ghost">Убрать</button></form></td></tr><?php endforeach;?><?php if(empty($options[$gid])):?><tr><td colspan="5" class="muted">Добавьте товары, которые уже существуют в Kapouch/Evotor.</td></tr><?php endif;?></tbody></table></div>
<form method="post" class="form-grid" style="margin-top:12px;padding:12px;border:1px dashed var(--line);border-radius:14px"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="option_save"><input type="hidden" name="modifier_group_id" value="<?=$gid?>"><label>Товар Evotor<select name="product_id" required><option value="">Выберите товар</option><?php foreach($products as $p):?><option value="<?=$p['id']?>"><?=e($p['name'].' · '.money((float)$p['sale_price']).(!$p['active']?' · отключён':''))?></option><?php endforeach;?></select></label><label>Название в PWA<input name="label" placeholder="Например: Овсяное"></label><label>Порядок<input type="number" name="sort_order" value="100"></label><label style="display:flex;align-items:center;gap:8px"><input style="width:auto" type="checkbox" name="active" checked> Активен</label><div><button class="btn primary">Добавить товар</button></div></form></div>
<?php endforeach;?>
<div class="two-col section"><div class="card"><div class="chart-head"><div><h2>Подключить к напитку с объёмами</h2><p>Группа модификаторов будет доступна для всех 250/350/450 мл.</p></div></div><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="assign_group"><label>Напиток<select name="product_group_id" required><option value="">Выберите группу</option><?php foreach($displayGroups as $p):?><option value="<?=$p['id']?>"><?=e($p['name'])?></option><?php endforeach;?></select></label><label>Модификаторы<select name="modifier_group_id" required><option value="">Выберите группу</option><?php foreach($groups as $g):?><option value="<?=$g['id']?>"><?=e($g['name'])?></option><?php endforeach;?></select></label><div><button class="btn primary">Подключить</button></div></form></div><div class="card"><div class="chart-head"><div><h2>Подключить к отдельному товару</h2><p>Например только к конкретному размеру или позиции без группы.</p></div></div><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="assign_product"><label>Товар<select name="product_id" required><option value="">Выберите товар</option><?php foreach($products as $p):?><option value="<?=$p['id']?>"><?=e($p['name'])?></option><?php endforeach;?></select></label><label>Модификаторы<select name="modifier_group_id" required><option value="">Выберите группу</option><?php foreach($groups as $g):?><option value="<?=$g['id']?>"><?=e($g['name'])?></option><?php endforeach;?></select></label><div><button class="btn primary">Подключить</button></div></form></div></div>
<div class="card section"><div class="chart-head"><div><h2>Текущие привязки</h2></div></div><div style="overflow:auto"><table><thead><tr><th>К чему</th><th>Группа модификаторов</th><th></th></tr></thead><tbody><?php foreach($assignGroups as $a):?><tr><td><strong><?=e($a['product_group_name'])?></strong><div class="muted">все объёмы</div></td><td><?=e($a['modifier_group_name'])?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="assignment_delete"><input type="hidden" name="target_type" value="group"><input type="hidden" name="target_id" value="<?=$a['product_group_id']?>"><input type="hidden" name="modifier_group_id" value="<?=$a['modifier_group_id']?>"><button class="btn ghost">Убрать</button></form></td></tr><?php endforeach;?><?php foreach($assignProducts as $a):?><tr><td><strong><?=e($a['product_name'])?></strong><div class="muted">конкретный товар</div></td><td><?=e($a['modifier_group_name'])?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="assignment_delete"><input type="hidden" name="target_type" value="product"><input type="hidden" name="target_id" value="<?=$a['product_id']?>"><input type="hidden" name="modifier_group_id" value="<?=$a['modifier_group_id']?>"><button class="btn ghost">Убрать</button></form></td></tr><?php endforeach;?><?php if(!$assignGroups&&!$assignProducts):?><tr><td colspan="3" class="muted">Модификаторы пока не подключены к напиткам.</td></tr><?php endif;?></tbody></table></div></div>
<?php page_footer();?>
