<?php
require __DIR__.'/inc/bootstrap.php';
require __DIR__.'/inc/layout.php';
require_auth();
require_once __DIR__.'/inc/customer_modifiers.php';

if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$action=(string)($_POST['action']??'');
    try{
        if($action==='group_save'){
            $id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));if($name==='')throw new RuntimeException('Укажите название группы.');
            $min=max(0,min(10,(int)($_POST['min_select']??0)));$max=max(1,min(10,(int)($_POST['max_select']??1)));if($min>$max)$min=$max;$sort=(int)($_POST['sort_order']??100);$active=isset($_POST['active'])?1:0;
            if($id){db()->prepare('UPDATE customer_modifier_groups SET name=?,min_select=?,max_select=?,sort_order=?,active=? WHERE id=?')->execute([$name,$min,$max,$sort,$active,$id]);}
            else{db()->prepare('INSERT INTO customer_modifier_groups(name,min_select,max_select,sort_order,active) VALUES(?,?,?,?,?)')->execute([$name,$min,$max,$sort,$active]);}
            flash('success','Группа модификаторов сохранена.');
        }elseif($action==='option_save'){
            $groupId=(int)($_POST['modifier_group_id']??0);$productId=(int)($_POST['product_id']??0);$label=mb_substr(trim((string)($_POST['label']??'')),0,120);
            if($groupId<=0||$productId<=0)throw new RuntimeException('Выберите группу и товар Evotor.');if($label==='')throw new RuntimeException('Укажите название варианта в PWA, например «Карамель».');
            $check=db()->prepare('SELECT evotor_product_id FROM evotor_products WHERE local_product_id=? ORDER BY id LIMIT 1');$check->execute([$productId]);$evotorId=(string)($check->fetchColumn()?:'');if($evotorId==='')throw new RuntimeException('Этот товар не связан с номенклатурой Evotor.');
            db()->prepare('INSERT INTO customer_modifier_options(modifier_group_id,product_id,label,sort_order,active) VALUES(?,?,?,?,?)')->execute([$groupId,$productId,$label,(int)($_POST['sort_order']??100),isset($_POST['active'])?1:0]);
            if(isset($_POST['hide_in_catalog']))db()->prepare('INSERT INTO customer_product_settings(product_id,visible) VALUES(?,0) ON DUPLICATE KEY UPDATE visible=0')->execute([$productId]);
            audit_write('customer_modifier_option_saved','Вариант «'.$label.'» → Evotor '.$evotorId,'product',(string)$productId);flash('success','Вариант «'.$label.'» добавлен. Один товар Evotor можно использовать для других вкусов ещё раз.');
        }elseif($action==='option_delete'){
            db()->prepare('DELETE FROM customer_modifier_options WHERE id=?')->execute([(int)($_POST['id']??0)]);flash('success','Вариант удалён.');
        }elseif($action==='assign_group'){
            $target=(int)($_POST['product_group_id']??0);$group=(int)($_POST['modifier_group_id']??0);if(!$target||!$group)throw new RuntimeException('Выберите напиток и модификаторы.');db()->prepare('INSERT IGNORE INTO customer_display_group_modifier_groups(product_group_id,modifier_group_id) VALUES(?,?)')->execute([$target,$group]);flash('success','Модификаторы подключены ко всем объёмам.');
        }elseif($action==='assign_product'){
            $target=(int)($_POST['product_id']??0);$group=(int)($_POST['modifier_group_id']??0);if(!$target||!$group)throw new RuntimeException('Выберите товар и модификаторы.');db()->prepare('INSERT IGNORE INTO customer_product_modifier_groups(product_id,modifier_group_id) VALUES(?,?)')->execute([$target,$group]);flash('success','Модификаторы подключены к товару.');
        }elseif($action==='assignment_delete'){
            $type=(string)($_POST['target_type']??'');$target=(int)($_POST['target_id']??0);$group=(int)($_POST['modifier_group_id']??0);
            if($type==='group')db()->prepare('DELETE FROM customer_display_group_modifier_groups WHERE product_group_id=? AND modifier_group_id=?')->execute([$target,$group]);
            if($type==='product')db()->prepare('DELETE FROM customer_product_modifier_groups WHERE product_id=? AND modifier_group_id=?')->execute([$target,$group]);flash('success','Привязка удалена.');
        }
    }catch(Throwable $e){flash('danger',$e->getMessage());}
    redirect('customer_modifiers.php');
}

$groups=customer_modifier_groups(false);$products=db()->query('SELECT id,name,sale_price,active FROM products ORDER BY active DESC,name')->fetchAll();
$evotorProducts=db()->query("SELECT p.id,p.name,p.sale_price,p.active,MIN(ep.evotor_product_id) evotor_product_id FROM products p JOIN evotor_products ep ON ep.local_product_id=p.id GROUP BY p.id,p.name,p.sale_price,p.active ORDER BY p.active DESC,p.name")->fetchAll();
$displayGroups=db()->query('SELECT id,name FROM customer_product_groups ORDER BY sort_order,name')->fetchAll();$options=[];foreach($groups as $g)$options[(int)$g['id']]=customer_modifier_options((int)$g['id'],false);
$assignGroups=db()->query('SELECT a.product_group_id,a.modifier_group_id,p.name product_group_name,m.name modifier_group_name FROM customer_display_group_modifier_groups a JOIN customer_product_groups p ON p.id=a.product_group_id JOIN customer_modifier_groups m ON m.id=a.modifier_group_id ORDER BY p.name,m.name')->fetchAll();
$assignProducts=db()->query('SELECT a.product_id,a.modifier_group_id,p.name product_name,m.name modifier_group_name FROM customer_product_modifier_groups a JOIN products p ON p.id=a.product_id JOIN customer_modifier_groups m ON m.id=a.modifier_group_id ORDER BY p.name,m.name')->fetchAll();
page_header('Модификаторы PWA');
?>
<div class="card"><div class="chart-head"><div><h2>Модификаторы из Evotor</h2><p>Один товар Evotor может обслуживать сколько угодно вариантов PWA. Например «Сироп» → Карамель, Ваниль, Орех.</p></div><a class="btn ghost" href="customer_app.php">← Клиентское PWA</a></div></div>
<div class="alert info section"><strong>Пример:</strong> создайте группу «Сиропы», затем несколько раз выберите один и тот же товар Evotor «Сироп», но задайте разные названия PWA: «Карамель», «Ваниль», «Лесной орех». Цена у всех будет одна — текущая цена товара «Сироп».</div>
<div class="card section"><h2>Новая группа</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="group_save"><label>Название<input name="name" required placeholder="Сиропы"></label><label>Минимум<input type="number" min="0" max="10" name="min_select" value="0"></label><label>Максимум<input type="number" min="1" max="10" name="max_select" value="1"></label><label>Порядок<input type="number" name="sort_order" value="100"></label><label><input style="width:auto" type="checkbox" name="active" checked> Активна</label><div><button class="btn primary">Создать</button></div></form></div>
<?php foreach($groups as $g):$gid=(int)$g['id'];?>
<div class="card section"><div class="chart-head"><div><h2><?=e($g['name'])?></h2><p>Можно выбрать <?=$g['min_select']?>–<?=$g['max_select']?> · вариантов <?=count($options[$gid]??[])?></p></div></div>
<form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="group_save"><input type="hidden" name="id" value="<?=$gid?>"><label>Название<input name="name" value="<?=e($g['name'])?>"></label><label>Минимум<input type="number" name="min_select" value="<?=$g['min_select']?>"></label><label>Максимум<input type="number" name="max_select" value="<?=$g['max_select']?>"></label><label>Порядок<input type="number" name="sort_order" value="<?=$g['sort_order']?>"></label><label><input style="width:auto" type="checkbox" name="active" <?=$g['active']?'checked':''?>> Активна</label><div><button class="btn ghost">Сохранить</button></div></form>
<div style="overflow:auto;margin-top:14px"><table><thead><tr><th>Вариант PWA</th><th>Товар Evotor</th><th>Цена</th><th>Evotor ID</th><th></th></tr></thead><tbody><?php foreach($options[$gid]??[] as $o):?><tr><td><strong><?=e($o['label'])?></strong></td><td><?=e($o['product_name'])?></td><td><?=money((float)$o['sale_price'])?></td><td class="muted"><?=e((string)($o['evotor_product_id']??'—'))?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="option_delete"><input type="hidden" name="id" value="<?=$o['id']?>"><button class="btn ghost">Убрать</button></form></td></tr><?php endforeach;?><?php if(empty($options[$gid])):?><tr><td colspan="5" class="muted">Вариантов пока нет.</td></tr><?php endif;?></tbody></table></div>
<form method="post" class="form-grid" style="margin-top:12px;padding:12px;border:1px dashed var(--line);border-radius:14px"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="option_save"><input type="hidden" name="modifier_group_id" value="<?=$gid?>"><label>Товар Evotor<select name="product_id" required><option value="">Выберите товар</option><?php foreach($evotorProducts as $p):?><option value="<?=$p['id']?>"><?=e($p['name'].' · '.money((float)$p['sale_price']))?></option><?php endforeach;?></select></label><label>Название варианта в PWA<input name="label" required placeholder="Карамель"></label><label>Порядок<input type="number" name="sort_order" value="100"></label><label><input style="width:auto" type="checkbox" name="active" checked> Активен</label><label><input style="width:auto" type="checkbox" name="hide_in_catalog" checked> Скрыть товар Evotor как отдельную позицию PWA</label><div><button class="btn primary">Добавить вариант</button></div></form>
</div><?php endforeach;?>
<div class="two-col section"><div class="card"><h2>Подключить ко всем объёмам</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="assign_group"><label>Напиток<select name="product_group_id" required><option value="">Выберите</option><?php foreach($displayGroups as $p):?><option value="<?=$p['id']?>"><?=e($p['name'])?></option><?php endforeach;?></select></label><label>Модификаторы<select name="modifier_group_id" required><option value="">Выберите</option><?php foreach($groups as $g):?><option value="<?=$g['id']?>"><?=e($g['name'])?></option><?php endforeach;?></select></label><div><button class="btn primary">Подключить</button></div></form></div><div class="card"><h2>Подключить к одному товару</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="assign_product"><label>Товар<select name="product_id" required><option value="">Выберите</option><?php foreach($products as $p):?><option value="<?=$p['id']?>"><?=e($p['name'])?></option><?php endforeach;?></select></label><label>Модификаторы<select name="modifier_group_id" required><option value="">Выберите</option><?php foreach($groups as $g):?><option value="<?=$g['id']?>"><?=e($g['name'])?></option><?php endforeach;?></select></label><div><button class="btn primary">Подключить</button></div></form></div></div>
<div class="card section"><h2>Текущие привязки</h2><div style="overflow:auto"><table><thead><tr><th>Напиток / товар</th><th>Группа</th><th></th></tr></thead><tbody><?php foreach($assignGroups as $a):?><tr><td><?=e($a['product_group_name'])?> <span class="muted">· все объёмы</span></td><td><?=e($a['modifier_group_name'])?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="assignment_delete"><input type="hidden" name="target_type" value="group"><input type="hidden" name="target_id" value="<?=$a['product_group_id']?>"><input type="hidden" name="modifier_group_id" value="<?=$a['modifier_group_id']?>"><button class="btn ghost">Убрать</button></form></td></tr><?php endforeach;?><?php foreach($assignProducts as $a):?><tr><td><?=e($a['product_name'])?></td><td><?=e($a['modifier_group_name'])?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="assignment_delete"><input type="hidden" name="target_type" value="product"><input type="hidden" name="target_id" value="<?=$a['product_id']?>"><input type="hidden" name="modifier_group_id" value="<?=$a['modifier_group_id']?>"><button class="btn ghost">Убрать</button></form></td></tr><?php endforeach;?><?php if(!$assignGroups&&!$assignProducts):?><tr><td colspan="3" class="muted">Привязок пока нет.</td></tr><?php endif;?></tbody></table></div></div>
<?php page_footer();?>
