<?php
require __DIR__.'/inc/bootstrap.php';
require __DIR__.'/inc/layout.php';
require_auth();
require_once __DIR__.'/inc/customer_payments.php';

if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{
        $cash=isset($_POST['cash_enabled'])?'1':'0';$sbp=isset($_POST['sbp_enabled'])?'1':'0';if($cash==='0'&&$sbp==='0')throw new RuntimeException('Оставьте включённым хотя бы один способ оплаты.');
        set_app_setting('customer_payment_cash_enabled',$cash);set_app_setting('customer_payment_sbp_enabled',$sbp);set_app_setting('customer_payment_evotor_fiscalization_enabled',isset($_POST['evotor_fiscalization_enabled'])?'1':'0');
        set_app_setting('customer_payment_vat_code',(string)max(1,min(12,(int)($_POST['vat_code']??1))));set_app_setting('customer_payment_subject',(string)($_POST['payment_subject']??'commodity'));set_app_setting('customer_payment_mode',(string)($_POST['payment_mode']??'full_payment'));
        customer_payment_save_yookassa(['enabled'=>$sbp==='1','shop_id'=>(string)($_POST['shop_id']??''),'secret_key'=>(string)($_POST['secret_key']??'')]);
        audit_write('customer_payment_settings','Обновлены способы оплаты ЮKassa и фискализация PWA');flash('success','Настройки оплаты сохранены.');
    }catch(Throwable $e){flash('danger',$e->getMessage());}
    redirect('customer_payments.php');
}
$connection=customer_payment_connection('yookassa_sbp');$cashEnabled=app_setting('customer_payment_cash_enabled','1')==='1';$sbpEnabled=app_setting('customer_payment_sbp_enabled','0')==='1';$evotorFiscalization=customer_payment_evotor_fiscalization_enabled();$hasSecret=!empty($connection['secret_ciphertext']);$vat=(int)app_setting('customer_payment_vat_code','1');$subject=(string)app_setting('customer_payment_subject','commodity');$mode=(string)app_setting('customer_payment_mode','full_payment');
try{$webhook=customer_payment_public_url('api/customer_payment_yookassa_webhook.php');}catch(Throwable $e){$webhook='https://kapouch.store/api/customer_payment_yookassa_webhook.php';}
page_header('Оплата в PWA');
?>
<div class="card"><div class="chart-head"><div><h2>Способы оплаты</h2><p>Наличные и СБП включаются независимо. Онлайн-платежи теперь проходят через ЮKassa.</p></div><a class="btn ghost" href="customer_app.php">← Клиентское PWA</a></div></div>
<div class="alert info section"><strong>Схема:</strong> Kapouch → ЮKassa → СБП → ваш расчётный счёт. Секретный ключ хранится зашифрованным и после сохранения не показывается.</div>
<form method="post" class="section"><input type="hidden" name="csrf" value="<?=csrf_token()?>">
<div class="two-col"><div class="card"><h2>Наличными при самовывозе</h2><p class="muted">Заказ сразу попадает бариста со статусом «Не оплачено».</p><label style="display:flex;gap:9px;align-items:center"><input type="checkbox" name="cash_enabled" value="1" style="width:auto" <?=$cashEnabled?'checked':''?>> Разрешить оплату наличными</label></div><div class="card"><h2>Онлайн по СБП · ЮKassa</h2><p class="muted">Заказ появляется у бариста только после подтверждённой оплаты.</p><label style="display:flex;gap:9px;align-items:center"><input type="checkbox" name="sbp_enabled" value="1" style="width:auto" <?=$sbpEnabled?'checked':''?>> Показывать клиентам «Онлайн по СБП»</label></div></div>
<div class="card section"><div class="chart-head"><div><h2>Подключение ЮKassa</h2><p>Данные берутся в личном кабинете ЮKassa: shopId и секретный ключ API.</p></div><span class="pill <?=$sbpEnabled&&$hasSecret?'connected':''?>"><?=$sbpEnabled&&$hasSecret?'Подключено':'Не настроено'?></span></div><div class="form-grid"><label>shopId<input name="shop_id" value="<?=e((string)($connection['merchant_login']??''))?>" autocomplete="off" placeholder="Идентификатор магазина"></label><label>Секретный ключ<input type="password" name="secret_key" autocomplete="new-password" placeholder="<?=$hasSecret?'Оставьте пустым, чтобы не менять':'Секретный ключ ЮKassa'?>"></label></div></div>
<div class="card section"><div class="chart-head"><div><h2>Фискализация · Эвотор</h2><p>Если в ЮKassa подключена «Цифровая касса Эвотор», Kapouch передаст состав заказа в объекте receipt.</p></div><span class="pill <?=$evotorFiscalization?'connected':''?>"><?=$evotorFiscalization?'Включено':'Выключено'?></span></div><label style="display:flex;gap:9px;align-items:flex-start"><input type="checkbox" name="evotor_fiscalization_enabled" value="1" style="width:auto;margin-top:3px" <?=$evotorFiscalization?'checked':''?>><span><strong>Передавать чек ЮKassa → Цифровая касса Эвотор</strong><br><span class="muted">Включайте после подключения Эвотора в настройках 54-ФЗ личного кабинета ЮKassa.</span></span></label><div class="form-grid" style="margin-top:14px"><label>НДС<select name="vat_code"><?php foreach([1=>'Без НДС',2=>'0%',3=>'10%',7=>'5%',8=>'7%',11=>'22%'] as $k=>$v):?><option value="<?=$k?>" <?=$vat===$k?'selected':''?>><?=e($v)?></option><?php endforeach;?></select></label><label>Предмет расчёта<select name="payment_subject"><option value="commodity" <?=$subject==='commodity'?'selected':''?>>Товар</option><option value="service" <?=$subject==='service'?'selected':''?>>Услуга</option><option value="another" <?=$subject==='another'?'selected':''?>>Иное</option></select></label><label>Способ расчёта<select name="payment_mode"><option value="full_payment" <?=$mode==='full_payment'?'selected':''?>>Полный расчёт</option><option value="full_prepayment" <?=$mode==='full_prepayment'?'selected':''?>>Полная предоплата</option><option value="advance" <?=$mode==='advance'?'selected':''?>>Аванс</option></select></label></div></div>
<div class="card section"><h2>Webhook ЮKassa</h2><p class="muted">Укажите этот адрес в личном кабинете ЮKassa для уведомлений о платежах:</p><div class="token-box" style="margin-top:10px;letter-spacing:0;word-break:break-all"><?=e($webhook)?></div><p class="muted">Kapouch не доверяет входящему уведомлению вслепую: после webhook он запрашивает платёж обратно через API ЮKassa и сверяет статус и сумму.</p></div>
<div class="card section"><div class="actions"><button class="btn primary">Сохранить оплату</button><a class="btn ghost" href="customer/" target="_blank">Открыть PWA ↗</a></div></div></form>
<?php page_footer();?>