apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'

    defaultConfig {
        applicationId 'ru.kapouch.evotor'
        minSdkVersion 21
        targetSdkVersion 25
        versionCode 13
        versionName '1.2.6'
        manifestPlaceholders = [evotorAppUuid: project.hasProperty('EVOTOR_APP_UUID') ? project.property('EVOTOR_APP_UUID') : 'bc17ef43-f590-49ca-a6f2-e940f57d0a72']
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'com.github.evotor:push-notifications:v0.2.1'
}
